# Standard Jekyll / GitHub Pages
url: "https://senegalais-amiens.fr" # Le domaine racine
baseurl: ""                   # Le nom du dossier du projet

# Configuration de la langue (SEO)
lang: "fr_FR"
locale: "fr_FR"

# Informations SEO du site
title: "ASSOCIATION DES SENEGALAIS D'AMIENS"
description: "Site officiel de l'Association des Sénégalais d'Amiens (ASA)."

# Personnalisation des titres générés par jekyll-seo-tag
title_separator: "|"

# Autoriser la génération des pages avec une date dans le futur
future: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag # plugin officiel SEO de GitHub Pages.

# Déclaration de la collection "evenements"
collections:
  evenements:
    output: true
    permalink: /evenements/:name/

# UN SEUL bloc defaults, avec toutes les règles à la suite
defaults:
  - scope:
      path: "documents"
    values:
      sitemap: false
  - scope:
      path: ""
      type: evenements
    values:
      layout: evenement