# Standard Jekyll / GitHub Pages
url: "https://senegalais-amiens.fr" # Le domaine racine
baseurl: "/"                   # Le nom du dossier du projet

# Configuration de la langue (SEO)
lang: "fr_FR"
locale: "fr_FR"

# Informations SEO du site
title: "ASA - Association des Sénégalais d'Amiens"
description: "Site officiel de l'Association des Sénégalais d'Amiens (ASA)."

# Personnalisation des titres générés par jekyll-seo-tag
title_separator: "|"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag # plugin officiel SEO de GitHub Pages.


# Exclusion globale pour le plugin jekyll-sitemap
sitemap:
  exclude:
    - "/agenda-test.html"      # Une page spécifique
    - "/documents*"       # Tout un dossier
    - "/attestation-confirmation.html"     # Une URL spécifique
    - "*.json"                 # Tous les fichiers JSON
    - "404.html"               # La page d'erreur 404 (il l'est par défaut)

# Application de "sitemap: false" en masse
defaults:
  - scope:
      path: "documents" # Cible tout le contenu du dossier documents
    values:
      sitemap: false    # Exclut du sitemap
  - scope:
      path: "agenda-test.html" # Cible un fichier spécifique
    values:
      sitemap: false
  - scope:
      path: "adhesion-confirmation"
    values:
      sitemap: false