# Standard Jekyll / GitHub Pages
url: "https://senegalais-amiens.fr" # Le domaine racine
baseurl: "/"                   # Le nom du dossier du projet (sans slash à la fin)

title: "ASA l'Association"
description: "ASA - Association des Sénégalais d'Amiens."

plugins:
  - jekyll-sitemap